/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (5.0.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.image.portal.api;

import com.image.portal.model.Album;
import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import io.swagger.annotations.ApiResponse;
import io.swagger.annotations.ApiResponses;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.GetMapping;

import java.util.List;

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2021-03-24T09:41:07" +
        ".734618300-05:00[America/Chicago]")
@Validated
@Api(value = "albums", description = "the albums API")
public interface AlbumsApi {

    default AlbumsApiDelegate getDelegate() {
        return new AlbumsApiDelegate() {
        };
    }

    /**
     * GET /albums/ : get all albums
     * Returns all albums
     *
     * @return successful operation (status code 200)
     */
    @ApiOperation(value = "get all albums", nickname = "getAlbums", notes = "Returns all albums", response =
            Album.class, responseContainer = "List", tags = {"all albums page",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "successful operation", response = Album.class, responseContainer =
                    "List")})
    @GetMapping(
            value = "/albums/",
            produces = {"application/json"}
    )
    default ResponseEntity<List<Album>> getAlbums() {
        return getDelegate().getAlbums();
    }

}
